config/routes.rb
ScottishEntrepreneurialSupportNetwork::Application.routes.draw do

  resources :footers

  root "home#index"
  get "embed", to: "home#embed", as: "embed"

  get  "login",   to: "login#index",  as: "login"
  get  "logout",  to: "login#logout", as: "logout"
  post "login",   to: "login#login"
  get  "signup",  to: "login#signup", as: "signup"
  post "signup", to: "login#signup"

  namespace :admin do
    root 'organisations#index'
    get "/organisations/tree(.:format)", to: "organisations#tree", as: "tree_organisation"
    get "preferences", to: "preferences#index", as: "preferences"
    patch "preferences", to: "preferences#update"
    put   "preferences", to: "preferences#update", as: "update_preferences"
    resources :organisations
    resources :tags
    resources :categories
    resources :footers
    resources :headers
    resources :search_types do
      resources :searches
    end
  end

end

app/models/header.rb
class Header < ActiveRecord::Base
  has_attached_file :image, :styles => { :thumb => "128x128#" }
end

app/controllers/admin/headers_controller.rb
class Admin::HeadersController < Admin::AdminController
  #before_action :set_header, only: [:show, :edit, :update, :destroy]
  before_action :set_header, only: [:show, :edit, :destroy]

  # GET /headers
  # GET /headers.json
  def index
    @headers = Header.all
  end

  # GET /headers/1
  # GET /headers/1.json
  def show
  end

  # GET /headers/new
  def new
    @header = Header.new
  end

  # POST /headers
  # POST /headers.json
  def create
    @header = Header.new(header_params)

    respond_to do |format|
      if @header.save
        format.html { redirect_to admin_header_path(@header.id), notice: 'Header was successfully created.' }
        format.json { render action: 'show', status: :created, location: @header }
      else
        format.html { render action: 'new' }
        format.json { render json: @header.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /headers/1
  # DELETE /headers/1.json
  def destroy
    @header.destroy
    respond_to do |format|
      format.html { redirect_to admin_headers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_header
      @header = Header.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def header_params
      params.require(:header).permit(:image, :title, :subtitle)
    end
end

app/views/admin/headers/_form.html.erb
<%= simple_form_for(@header, :url => admin_headers_path) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :title %>
    <%= f.input :subtitle %>
    <%= f.input :image %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/headers/edit.html.erb
<h1>Edit the header</h1>

<%= render 'form' %>

<%= link_to 'Show', @header %> |
<%= link_to 'Back', admin_headers_path %>

app/views/admin/headers/index.html.erb
<h1>Change the Header</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Image</th>
    </tr>
  </thead>

  <tbody>
    <% @headers.each do |header| %>
      <tr>
        <td><%= header.title %></td>
        <td><%= header.subtitle %></td>
        <td><%= image_tag header.image(:thumb) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if @headers.first %>
  <%= link_to 'Delete Header', admin_header_path(@headers.first.id), :method => :delete %>
<% else %>
  <%= link_to 'Set Header', new_admin_header_path %>
<% end %>

app/views/admin/headers/new.html.erb
<h1>New header</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_headers_path %>

app/views/admin/headers/show.html.erb
<p>
  <strong>Image:</strong>
  <%= image_tag @header.image(:thumb) %>
</p>

<%= link_to 'Edit', edit_admin_header_path(@header) %> |
<%= link_to 'Back', admin_headers_path %>