config/routes.rb
ScottishEntrepreneurialSupportNetwork::Application.routes.draw do

  resources :footers

  root "home#index"
  get "embed", to: "home#embed", as: "embed"

  get  "login",   to: "login#index",  as: "login"
  get  "logout",  to: "login#logout", as: "logout"
  post "login",   to: "login#login"
  get  "signup",  to: "login#signup", as: "signup"
  post "signup", to: "login#signup"

  namespace :admin do
    root 'organisations#index'
    get "/organisations/tree(.:format)", to: "organisations#tree", as: "tree_organisation"
    get "preferences", to: "preferences#index", as: "preferences"
    patch "preferences", to: "preferences#update"
    put   "preferences", to: "preferences#update", as: "update_preferences"
    resources :organisations
    resources :tags
    resources :categories
    resources :footers
    resources :headers
    resources :search_types do
      resources :searches
    end
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  default_scope { where type: nil } # Remove the child STI tables from all results
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::AdminController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to admin_tag_path(@tag), notice: 'Tag was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tag }
      else
        format.html { render action: 'new' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to admin_tag_path(@tag), notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to admin_tags_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tag }
      else
        format.html { render action: 'new' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/admin/tags/_form.html.erb
<%= simple_form_for([:admin, @tag]) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :name %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/tags/edit.html.erb
<h3>Editing Tag</h3>

<%= render 'form' %>

<%= link_to 'Show', admin_tag_path(@tag) %> |
<%= link_to 'Back', admin_tags_path %>

app/views/admin/tags/index.html.erb
<h3>Listing tags</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', admin_tag_path(tag) %></td>
        <td><%= link_to 'Edit', edit_admin_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', admin_tag_path(tag), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_admin_tag_path %>

app/views/admin/tags/new.html.erb
<h3>New tag</h3>

<%= render 'form' %>

<%= link_to 'Back', admin_tags_path %>

app/views/admin/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_admin_tag_path(@tag) %> |
<%= link_to 'Back', admin_tags_path %>