config/routes.rb
ScottishEntrepreneurialSupportNetwork::Application.routes.draw do

  resources :footers

  root "home#index"
  get "embed", to: "home#embed", as: "embed"

  get  "login",   to: "login#index",  as: "login"
  get  "logout",  to: "login#logout", as: "logout"
  post "login",   to: "login#login"
  get  "signup",  to: "login#signup", as: "signup"
  post "signup", to: "login#signup"

  namespace :admin do
    root 'organisations#index'
    get "/organisations/tree(.:format)", to: "organisations#tree", as: "tree_organisation"
    get "preferences", to: "preferences#index", as: "preferences"
    patch "preferences", to: "preferences#update"
    put   "preferences", to: "preferences#update", as: "update_preferences"
    resources :organisations
    resources :tags
    resources :categories
    resources :footers
    resources :headers
    resources :search_types do
      resources :searches
    end
  end

end

app/controllers/admin/search_types_controller.rb
class Admin::SearchTypesController < Admin::AdminController
  before_action :set_search_type, only: [:show, :edit, :update, :destroy]

  # GET /search_types
  # GET /search_types.json
  def index
    @search_types = SearchType.all
  end

  # GET /search_types/1
  # GET /search_types/1.json
  def show
  end

  # GET /search_types/new
  def new
    @search_type = SearchType.new
  end

  # GET /search_types/1/edit
  def edit
  end

  # POST /search_types
  # POST /search_types.json
  def create
    @search_type = SearchType.new(search_type_params)

    respond_to do |format|
      if @search_type.save
        format.html { redirect_to admin_search_type_path(@search_type), notice: 'SearchType was successfully created.' }
        format.json { render action: 'show', status: :created, location: @search_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @search_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /search_types/1
  # PATCH/PUT /search_types/1.json
  def update
    respond_to do |format|
      if @search_type.update(search_type_params)
        format.html { redirect_to admin_search_type_path(@search_type), notice: 'SearchType was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @search_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_types/1
  # DELETE /search_types/1.json
  def destroy
    @search_type.destroy
    respond_to do |format|
      format.html { redirect_to admin_search_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search_type
      @search_type = SearchType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_type_params
      params.require(:search_type).permit(:name)
    end
end

app/views/admin/search_types/_form.html.erb
<%= simple_form_for([:admin, @search_type]) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :name %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/search_types/edit.html.erb
<h3>Editing Search Type</h3>

<%= render 'form' %>

<%= link_to 'Show', admin_category_path(@category) %> |
<%= link_to 'Back', admin_categories_path %>

app/views/admin/search_types/index.html.erb
<h3>Listing Search Types</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @search_types.each do |search_type| %>
      <tr>
        <td><%= link_to search_type.name, admin_search_type_searches_path(search_type) %></td>
        <td><%= link_to 'Show', admin_search_type_path(search_type) %></td>
        <td><%= link_to 'Edit', edit_admin_search_type_path(search_type) %></td>
        <td><%= link_to 'Destroy', admin_search_type_path(search_type), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_admin_search_type_path %>

app/views/admin/search_types/new.html.erb
<h3>New Search Type</h3>

<%= render 'form' %>

<%= link_to 'Back', admin_search_types_path %>

app/views/admin/search_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @search_type.name %>
</p>

<%= link_to 'Edit', edit_admin_search_type_path(@search_type) %> |
<%= link_to 'Back', admin_search_types_path %>